- color: 495057
  name: automated pr
  description: Pull requests created by GitHub Actions
- color: 0b7285
  name: dependencies
  description: Pull requests that update dependencies
- color: 1864ab
  name: sync-template
  description: Pull requests that sync the template repository
